### PR TITLE
Fix detection of ZIO expressions

### LINKED ISSUE #185: "Unused expression" does not work for method calls with more than one argument
e.g.

```scala
  val y: ZIO[Console, Throwable, Unit] = {
    foo("a", "b") // <-- does not highlight 'foo' as unused
    putStrLn("oops")
  }

  def foo(arg: String, arg2: String): ZIO[Any, Nothing, Unit] = ???
```

changing `foo` to have 0 or just 1 argument makes the highlighting work.

edit: Upon further inspection it seems that `zioRef` does not handle methods with more than one argument... possibly related to the use of `Seq(e)` for arguments in the extractors?

### PR DESCRIPTION
**Pull request by myazinn**
Closes zio#185

### CODE REVIEW

File: src/main/scala/zio/intellij/inspections/mistakes/UnusedZIOExpressionsInspection.scala [hunk 1]
```diff
@@ -18,8 +17,8 @@ class UnusedZIOExpressionsInspection extends AbstractRegisteredInspection {
   )(implicit manager: InspectionManager, isOnTheFly: Boolean): Option[ProblemDescriptor] =
     element match {
       case expr: ScExpression =>
-        (expr, Option(expr.getNextSiblingNotWhitespace)) match {
-          case (zioRef(_, _), Some(zioRef(_, _))) =>
+        (expr, expr.nextSiblingNotWhitespace) match {
```
Comment (hmemcpy) [inline src/main/scala/zio/intellij/inspections/mistakes/UnusedZIOExpressionsInspection.scala:20]: Hah, I was about to suggest that :)

**Comment by hmemcpy** [comment]
Amazing, thank you so much for the fix! Looks like you've covered way more potential cases!
