### PR TITLE
fix subtyping issue in .provide(ZLayer) inspection

### LINKED ISSUE #412: False negative from inspection for .provideSome
The newly introduced inspections for .provideSome (https://github.com/zio/zio-intellij/pull/396 and https://github.com/zio/zio-intellij/pull/399) might report a problem when there is none.

We use ZIO 2.0.5

image

```scala
case class DatabaseLive(configService: ConfigService) extends Database {
  ....
}

object DatabaseLive {
  val layer: ZLayer[ConfigService, Nothing, DatabaseLive] = ZLayer {
    for configService <- ZIO.service[ConfigService]
      yield DatabaseLive(configService)
  }
}
```

image

### PR DESCRIPTION
**Pull request by myazinn**
Fixes https://github.com/zio/zio-intellij/issues/412

### CODE REVIEW

File: src/main/scala/zio/intellij/inspections/macros/ProvideMacroInspection.scala [hunk 1]
```diff
@@ -300,7 +300,7 @@ final case class LayerBuilder(
      */
     val layerTreeEither: Either[::[GraphError], LayerTree[ZExpr]] = {
       val nodes = providedLayerNodes ++ remainderNodes ++ sideEffectNodes
-      val graph = Graph(nodes, (l, r) => r.conforms(l))
+      val graph = Graph(nodes, _.isSubtypeOf(_))
```
Comment (myazinn) [inline src/main/scala/zio/intellij/inspections/macros/ProvideMacroInspection.scala:303]: Classic :(

**Review by hmemcpy — APPROVED** [review]
