### PR TITLE
fix NoClassDefFoundError and NoSuchMethodError errors

### LINKED ISSUE #496: NoClassDefFoundError in version eap zio-intellij for IntelliJ 2025.1
`NoClassDefFoundError` in version `zio-intellij` `2025.1.40.1755` on  `IntelliJ IDEA 2025.1 (Ultimate Edition)`:

```
Build #IU-251.23774.435, built on April 14, 2025
Source revision: 9b2a2c261c093
...
Runtime version: 21.0.6+9-b895.109 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
...
Non-Bundled Plugins:
  org.intellij.scala (2025.1.20)
  zio.intellij.zio-intellij (2025.1.40.1755)
```

```
org.jetbrains.plugins.scala.lang.psi.types.Context
Cannot read scheme com.intellij.configurationStore.SchemeManagerIprProvider: _template__ type_ ZIOTestRunConfiguration___ factoryName_ ZIO Test.xml

java.lang.NoClassDefFoundError: org/jetbrains/plugins/scala/lang/psi/types/Context
	at zio.intellij.testsupport.ZTestRunConfigurationFactory$$anonfun$createTemplateConfiguration$1.applyOrElse(ZTestRunConfigurationFactory.scala:20)
	at zio.intellij.testsupport.ZTestRunConfigurationFactory$$anonfun$createTemplateConfiguration$1.applyOrElse(ZTestRunConfigurationFactory.scala:19)
	at scala.collection.IterableOnceOps.collectFirst(IterableOnce.scala:1256)
	at scala.collection.IterableOnceOps.collectFirst$(IterableOnce.scala:1248)
	at scala.collection.AbstractIterable.collectFirst(Iterable.scala:935)
	at zio.intellij.testsupport.ZTestRunConfigurationFactory.createTemplateConfiguration(ZTestRunConfigurationFactory.scala:19)
	at com.intellij.execution.configurations.ConfigurationFactory.createTemplateConfiguration(ConfigurationFactory.java:67)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal(RunnerAndConfigurationSettingsImpl.kt:233)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal$default(RunnerAndConfigurationSettingsImpl.kt:215)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.readData(RunConfigurationSchemeManager.kt:69)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:51)
	at com.intellij.execution.impl.RunConfigurationSchemeManager.createScheme(RunConfigurationSchemeManager.kt:21)
	at com.intellij.configurationStore.LazySchemeProcessor.createScheme$default(scheme-impl.kt:65)
	at com.intellij.configurationStore.schemeManager.SchemeLoader.loadScheme(schemeLoader.kt:180)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadSchemes$lambda$8(SchemeManagerImpl.kt:250)
	at com.intellij.configurationStore.SchemeManagerIprProvider.processChildren$lambda$3(SchemeManagerIprProvider.kt:50)
	at com.intellij.configurationStore.SchemeManagerIprProviderKt.read(SchemeManagerIprProvider.kt:145)
	at com.intellij.configurationStore.SchemeManagerIprProviderKt.access$read(SchemeManagerIprProvider.kt:1)
	at com.intellij.configurationStore.SchemeManagerIprProvider.processChildren(SchemeManagerIprProvider.kt:48)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadSchemes(SchemeManagerImpl.kt:248)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.reload(SchemeManagerImpl.kt:297)
	at com.intellij.openapi.options.SchemeManager.reload(SchemeManager.kt:32)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:874)
	at com.intellij.execution.impl.RunManagerImpl.loadState(RunManagerImpl.kt:92)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:517)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:437)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:152)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:46)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeService$intellij_platform_serviceContainer(ComponentManagerImpl.kt:654)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance$lambda$1$lambda$0(ServiceInstanceInitializer.kt:69)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.withStoredTemporaryContext(instantiate.kt:306)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance$suspendImpl(ServiceInstanceInitializer.kt:68)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance(ServiceInstanceInitializer.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:163)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:161)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:27)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:90)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:146)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:14)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:136)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:96)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance$suspendImpl(LazyInstanceHolder.kt:84)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.instance(InstanceContainerImpl.kt:67)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:700)
	at com.intellij.openapi.components.ServicesKt.serviceAsync(services.kt:81)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer$execute$2$1.invokeSuspend(ProjectRunConfigurationInitializer.kt:41)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer$execute$2$1.invoke(ProjectRunConfigurationInitializer.kt)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer$execute$2$1.invoke(ProjectRunConfigurationInitializer.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:56)
	at com.intellij.idea.Main$startApp$2$1$1.span(Main.kt:100)
	at com.intellij.diagnostic.CoroutineTracerShim.span$default(CoroutineTracerShim.kt:31)
	at com.intellij.execution.impl.ProjectRunConfigurationInitializer$execute$2.invokeSuspend(ProjectRunConfigurationInitializer.kt:30)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.scala.lang.psi.types.Context PluginClassLoader(plugin=PluginDescriptor(name=ZIO for IntelliJ, id=zio.intellij.zio-intellij, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/zio-intellij, version=2025.1.40.1755, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaUltimate.js, descriptorPath=scalaUltimate.js.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=org.jetbrains.plugins.scala.scalajs, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaCommunity.maven, descriptorPath=scalaCommunity.maven.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=org.jetbrains.plugins.scala.project.maven, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaCommunity.markdown, descriptorPath=scalaCommunity.markdown.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=org.jetbrains.plugins.scala.markdown, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaUltimate.debugger-collection-visualization, descriptorPath=scalaUltimate.debugger-collection-visualization.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=org.jetbrains.plugins.scala.debugger.collections.visualizer, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaUltimate.coverage, descriptorPath=scalaUltimate.coverage.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=org.jetbrains.plugins.scala.coverage, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaUltimate.full-line, descriptorPath=scalaUltimate.full-line.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=org.jetbrains.completion.full.line.scala, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaUltimate.llm.maven, descriptorPath=scalaUltimate.llm.maven.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=com.intellij.ml.llm.scala.maven, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaUltimate.llm.gradle, descriptorPath=scalaUltimate.llm.gradle.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=com.intellij.ml.llm.scala.gradle, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaUltimate.llm-embeddings, descriptorPath=scalaUltimate.llm-embeddings.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=com.intellij.ml.llm.scala.embeddings, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaUltimate.llm-completion, descriptorPath=scalaUltimate.llm-completion.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=com.intellij.ml.llm.scala.completion.cloud, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaUltimate.llm, descriptorPath=scalaUltimate.llm.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=com.intellij.ml.llm.scala, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaUltimate.ml-inline-completion, descriptorPath=scalaUltimate.ml-inline-completion.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=com.intellij.ml.inline.completion.scala, isBundled=false), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.terminal, descriptorPath=intellij.java.terminal.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=251.23774.435, package=com.intellij.java.terminal, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.performancePlugin, descriptorPath=intellij.java.performancePlugin.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=251.23774.435, package=com.intellij.java.performancePlugin, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.debugger.impl.frontend, descriptorPath=intellij.java.debugger.impl.frontend.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=251.23774.435, package=com.intellij.java.debugger.impl.frontend, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.debugger.impl.backend, descriptorPath=intellij.java.debugger.impl.backend.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=251.23774.435, package=com.intellij.java.debugger.impl.backend, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.compiler.charts, descriptorPath=intellij.java.compiler.charts.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=251.23774.435, package=com.intellij.java.compiler.charts, isBundled=true), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaUltimate.evaluation, descriptorPath=scalaUltimate.evaluation.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=com.intellij.cce.scala, isBundled=false), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=/Applications/IntelliJ IDEA.app/Contents/lib, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=/Applications/IntelliJ IDEA.app/Contents/lib, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=/Applications/IntelliJ IDEA.app/Contents/lib, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=/Applications/IntelliJ IDEA.app/Contents/lib, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.jvm.analysis.impl, descriptorPath=intellij.jvm.analysis.impl.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.vcs, descriptorPath=intellij.java.vcs.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.unscramble, descriptorPath=intellij.java.unscramble.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.featuresTrainer, descriptorPath=intellij.java.featuresTrainer.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=Java, id=com.intellij.java, moduleName=intellij.java.structuralSearch, descriptorPath=intellij.java.structuralSearch.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaCommunity.intellij-bazel, descriptorPath=scalaCommunity.intellij-bazel.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=null, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaCommunity.bsp, descriptorPath=scalaCommunity.bsp.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=null, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaCommunity.compiler-integration, descriptorPath=scalaCommunity.compiler-integration.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=null, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaCommunity.debugger, descriptorPath=scalaCommunity.debugger.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=null, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaUltimate.js-debugger, descriptorPath=scalaUltimate.js-debugger.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=null, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaCommunity.worksheet, descriptorPath=scalaCommunity.worksheet.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=null, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaCommunity.scala-cli, descriptorPath=scalaCommunity.scala-cli.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=null, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaCommunity.testing-support, descriptorPath=scalaCommunity.testing-support.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=null, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaCommunity.bsp-terminal, descriptorPath=scalaCommunity.bsp-terminal.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=null, isBundled=false), PluginDescriptor(name=Scala, id=org.intellij.scala, moduleName=scalaCommunity.bsp-junit, descriptorPath=scalaCommunity.bsp-junit.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=null, isBundled=false), PluginDescriptor(name=Java, id=com.intellij.java, descriptorPath=plugin.xml, path=/Applications/IntelliJ IDEA.app/Contents/plugins/java, version=251.23774.435, package=null, isBundled=true), PluginDescriptor(name=Scala, id=org.intellij.scala, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/Scala, version=2025.1.20, package=null, isBundled=false), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:157)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 72 more
```

### LINKED ISSUE #497: Unhandled exception: java.lang.NoSuchMethodError: 'boolean org.jetbrains.plugins.scala.lang.psi.types.package$ScTypeExt$.conforms$extension(org.jetbrains.plugins.scala.lang.psi.types.ScType, org.jetbrains.plugins.scala.lang.psi.types.ScType)'
The following exceptions(s) occurred in the ZIO for IntelliJ plugin:

```
java.lang.NoSuchMethodError: 'boolean org.jetbrains.plugins.scala.lang.psi.types.package$ScTypeExt$.conforms$extension(org.jetbrains.plugins.scala.lang.psi.types.ScType, org.jetbrains.plugins.scala.lang.psi.types.ScType)'
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.$anonfun$conforms$1(SuggestTypeAlias.scala:101)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.$anonfun$conforms$1$adapted(SuggestTypeAlias.scala:101)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$$anonfun$$nestedInanonfun$check$2$1.applyOrElse(SuggestTypeAlias.scala:110)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$$anonfun$$nestedInanonfun$check$2$1.applyOrElse(SuggestTypeAlias.scala:110)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:338)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:334)
	at scala.Option.collect(Option.scala:462)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.$anonfun$check$2(SuggestTypeAlias.scala:110)
	at scala.Option.flatMap(Option.scala:283)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.check(SuggestTypeAlias.scala:106)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.conforms(SuggestTypeAlias.scala:101)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$$anonfun$1.applyOrElse(SuggestTypeAlias.scala:85)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$$anonfun$1.applyOrElse(SuggestTypeAlias.scala:84)
	at scala.collection.immutable.List.collect(List.scala:276)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.findMatchingAliases(SuggestTypeAlias.scala:84)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias.shouldSuggest(SuggestTypeAlias.scala:46)
	at zio.intellij.intentions.ZTypeAnnotationIntention.$anonfun$descriptionStrategy$1(ZTypeAnnotationIntention.scala:18)
	at zio.intellij.intentions.ZTypeAnnotationIntention.$anonfun$descriptionStrategy$1$adapted(ZTypeAnnotationIntention.scala:17)
	at zio.intellij.intentions.ZStrategy$$anon$1.canSuggest(ZTypeAnnotationIntention.scala:40)
	at zio.intellij.intentions.ZStrategy$$anon$1.valueWithType(ZTypeAnnotationIntention.scala:48)
	at org.jetbrains.plugins.scala.codeInsight.intention.types.AbstractTypeAnnotationIntention$.$anonfun$complete$2(AbstractTypeAnnotationIntention.scala:100)
	at scala.Option.foreach(Option.scala:437)
	at org.jetbrains.plugins.scala.codeInsight.intention.types.AbstractTypeAnnotationIntention$.complete(AbstractTypeAnnotationIntention.scala:97)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias.isAvailable(SuggestTypeAlias.scala:52)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:199)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getRegisteredIntentionActions$6(ShowIntentionsPass.java:379)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:269)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getRegisteredIntentionActions(ShowIntentionsPass.java:378)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:350)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:250)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:435)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:28)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:431)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction$lambda$11(AnyThreadWriteThreadingSupport.kt:522)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithTemporaryThreadLocal(AnyThreadWriteThreadingSupport.kt:204)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:522)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1064)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:421)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:680)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:755)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:711)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:77)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:420)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:395)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:834)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:197)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:393)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:267)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

```
### Additional information:
<details>

ZIO plugin version: 2025.1.40.0
Scala plugin version: 2025.1.731
ZIO version(s): 2.1.16, 2.1.15
Scala version(s): 2.13.16, 2.13.16
sbt version: 1.10.11
IntelliJ version: IntelliJ IDEA 2025.1
Build #IU-251.23774.435
Java version: 21.0.6+9-b895.109
Operating System: amd64 Linux (6.8.0-57-generic, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

### LINKED ISSUE #498: Unhandled exception: java.lang.NoSuchMethodError: 'boolean org.jetbrains.plugins.scala.lang.psi.types.package$ScTypeExt$.conforms$extension(org.jetbrains.plugins.scala.lang.psi.types.ScType, org.jetbrains.plugins.scala.lang.psi.types.ScType)'
The following exceptions(s) occurred in the ZIO for IntelliJ plugin:

```
java.lang.NoSuchMethodError: 'boolean org.jetbrains.plugins.scala.lang.psi.types.package$ScTypeExt$.conforms$extension(org.jetbrains.plugins.scala.lang.psi.types.ScType, org.jetbrains.plugins.scala.lang.psi.types.ScType)'
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.$anonfun$conforms$1(SuggestTypeAlias.scala:101)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.$anonfun$conforms$1$adapted(SuggestTypeAlias.scala:101)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$$anonfun$$nestedInanonfun$check$2$1.applyOrElse(SuggestTypeAlias.scala:110)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$$anonfun$$nestedInanonfun$check$2$1.applyOrElse(SuggestTypeAlias.scala:110)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:338)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:334)
	at scala.Option.collect(Option.scala:462)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.$anonfun$check$2(SuggestTypeAlias.scala:110)
	at scala.Option.flatMap(Option.scala:283)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.check(SuggestTypeAlias.scala:106)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.conforms(SuggestTypeAlias.scala:101)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$$anonfun$1.applyOrElse(SuggestTypeAlias.scala:85)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$$anonfun$1.applyOrElse(SuggestTypeAlias.scala:84)
	at scala.collection.immutable.List.collect(List.scala:276)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.findMatchingAliases(SuggestTypeAlias.scala:84)
	at zio.intellij.inspections.suggestions.SuggestTypeAliasInspection.zio$intellij$inspections$suggestions$SuggestTypeAliasInspection$$$anonfun$buildVisitor$1(SuggestTypeAliasInspection.scala:25)
	at zio.intellij.inspections.suggestions.SuggestTypeAliasInspection$$anonfun$buildVisitor$9.visitPsiElement(SuggestTypeAliasInspection.scala:21)
	at org.jetbrains.plugins.scala.codeInspection.package$PsiElementVisitorSimple.visitElement(package.scala:104)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:270)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiElementImpl.org$jetbrains$plugins$scala$lang$psi$api$ScalaPsiElement$$super$accept(ScalaPsiElementImpl.scala:25)
	at org.jetbrains.plugins.scala.lang.psi.api.ScalaPsiElement.accept(ScalaPsiElement.scala:108)
	at org.jetbrains.plugins.scala.lang.psi.api.ScalaPsiElement.accept$(ScalaPsiElement.scala:106)
	at org.jetbrains.plugins.scala.lang.psi.impl.ScalaPsiElementImpl.accept(ScalaPsiElementImpl.scala:25)
	at com.intellij.codeInsight.daemon.impl.InspectionVisitorOptimizer.lambda$acceptElements$1(InspectionVisitorOptimizer.java:196)
	at com.intellij.codeInsight.daemon.impl.InspectionVisitorOptimizer.acceptElements(InspectionVisitorOptimizer.java:207)
	at com.intellij.codeInsight.daemon.impl.InspectionVisitorOptimizer.acceptElements(InspectionVisitorOptimizer.java:196)
	at com.intellij.codeInspection.InspectionEngine.lambda$inspectElements$8(InspectionEngine.java:320)
	... 25 more
```
### Additional information:
<details>

ZIO plugin version: 2025.1.40.0
Scala plugin version: 2025.1.763
ZIO version(s): 2.1.17
Scala version(s): 3.4.1
sbt version: 1.10.0
IntelliJ version: IntelliJ IDEA 2025.1.1.1
Build #IU-251.25410.129
Java version: 21.0.6+9-b895.109
Operating System: aarch64 Mac OS X (15.4.1, aarch64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

### LINKED ISSUE #500: Unhandled exception: java.lang.NoSuchMethodError: 'boolean org.jetbrains.plugins.scala.lang.psi.types.package$ScTypeExt$.conforms$extension(org.jetbrains.plugins.scala.lang.psi.types.ScType, org.jetbrains.plugins.scala.lang.psi.types.ScType)'
The following exceptions(s) occurred in the ZIO for IntelliJ plugin:

```
java.lang.NoSuchMethodError: 'boolean org.jetbrains.plugins.scala.lang.psi.types.package$ScTypeExt$.conforms$extension(org.jetbrains.plugins.scala.lang.psi.types.ScType, org.jetbrains.plugins.scala.lang.psi.types.ScType)'
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.$anonfun$conforms$1(SuggestTypeAlias.scala:101)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.$anonfun$conforms$1$adapted(SuggestTypeAlias.scala:101)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$$anonfun$$nestedInanonfun$check$2$1.applyOrElse(SuggestTypeAlias.scala:110)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$$anonfun$$nestedInanonfun$check$2$1.applyOrElse(SuggestTypeAlias.scala:110)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:338)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:334)
	at scala.Option.collect(Option.scala:462)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.$anonfun$check$2(SuggestTypeAlias.scala:110)
	at scala.Option.flatMap(Option.scala:283)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.check(SuggestTypeAlias.scala:106)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.conforms(SuggestTypeAlias.scala:101)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$$anonfun$1.applyOrElse(SuggestTypeAlias.scala:85)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$$anonfun$1.applyOrElse(SuggestTypeAlias.scala:84)
	at scala.collection.immutable.List.collect(List.scala:276)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias$.findMatchingAliases(SuggestTypeAlias.scala:84)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias.shouldSuggest(SuggestTypeAlias.scala:46)
	at zio.intellij.intentions.ZTypeAnnotationIntention.$anonfun$descriptionStrategy$1(ZTypeAnnotationIntention.scala:18)
	at zio.intellij.intentions.ZTypeAnnotationIntention.$anonfun$descriptionStrategy$1$adapted(ZTypeAnnotationIntention.scala:17)
	at zio.intellij.intentions.ZStrategy$$anon$1.canSuggest(ZTypeAnnotationIntention.scala:40)
	at zio.intellij.intentions.ZStrategy$$anon$1.valueWithType(ZTypeAnnotationIntention.scala:48)
	at org.jetbrains.plugins.scala.codeInsight.intention.types.AbstractTypeAnnotationIntention$.$anonfun$complete$2(AbstractTypeAnnotationIntention.scala:100)
	at scala.Option.foreach(Option.scala:437)
	at org.jetbrains.plugins.scala.codeInsight.intention.types.AbstractTypeAnnotationIntention$.complete(AbstractTypeAnnotationIntention.scala:97)
	at zio.intellij.intentions.suggestions.SuggestTypeAlias.isAvailable(SuggestTypeAlias.scala:52)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:199)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getRegisteredIntentionActions$6(ShowIntentionsPass.java:379)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:269)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getRegisteredIntentionActions(ShowIntentionsPass.java:378)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:350)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:250)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:435)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:28)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:431)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction$lambda$11(AnyThreadWriteThreadingSupport.kt:522)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithTemporaryThreadLocal(AnyThreadWriteThreadingSupport.kt:204)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:522)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1064)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:421)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:680)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:755)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:711)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:77)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:420)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:395)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:834)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:197)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:393)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:267)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

```
### Additional information:
<details>

ZIO plugin version: 2025.1.40.0
Scala plugin version: 2025.1.791
ZIO version(s): 2.1.18
Scala version(s): 2.13.16
sbt version: 1.10.11
IntelliJ version: IntelliJ IDEA 2025.1.1.1
Build #IU-251.25410.129
Java version: 21.0.6+9-b895.109
Operating System: amd64 Linux (6.8.0-59-generic, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o.
</details>

### PR DESCRIPTION
**Pull request by myazinn**
this MR should fix `No...Error`s occurring due to new implicit `Context` parameter
fixes https://github.com/zio/zio-intellij/issues/496
fixes https://github.com/zio/zio-intellij/issues/497
fixes https://github.com/zio/zio-intellij/issues/498
fixes https://github.com/zio/zio-intellij/issues/500

### CODE REVIEW

**Comment by myazinn** [comment]
worked fine locally 😞 checking what went wrong

**Comment by hmemcpy** [comment]
hey, sorry I'm still away from the plugin, but if you haven't - please check out [this thread](https://discord.com/channels/931170831139217469/931171260824707072/1362342415704526979) where I reported the issue. I think they reverted the incompatible changes so a recompile might fix it all.

why the tests failing - have no idea, sorry :(

**Comment by myazinn** [comment]
@hmemcpy thanks, but my issue is entirely different 🤔 for some reason CI/CD uses some old IntelliJ version

**Comment by myazinn** [comment]
Actually never mind, you were right. I still have no idea why it worked fine locally, but oh well.
As for tests, I'll try to have a look this week (already attempted to find some easy fixes, but it seems it'll go a hard way),

File: src/main/scala/zio/intellij/utils/TypeCheckUtils.scala [hunk 1]
```diff
@@ -11,16 +11,27 @@ object TypeCheckUtils {
   val zioCompanionSpecificTypes      = List("zio.ZIOCompanionVersionSpecific", "zio.ZIOCompanionPlatformSpecific")
   val zioLayerCompanionSpecificTypes = List("zio.ZLayerCompanionVersionSpecific", "zio.magic.ZLayerCompanionOps")
 
-  val zioTypes        = ZioTypes.values.map(_.fqName) :+ "zio.ZIOPlatformSpecific" :+ "zio.ZIOVersionSpecific"
+  val zioTypes =
+    ZioTypes.values.map(_.fqName) :+
+      "zio.ZIOPlatformSpecific" :+
+      "zio.ZIOVersionSpecific" :+
+      "zio.ProvideSomeLayerPartiallyApplied"
```
Comment (myazinn) [inline src/main/scala/zio/intellij/utils/TypeCheckUtils.scala:19]: IntelliJ gets confused with partially applied methods in `org.jetbrains.plugins.scala.codeInspection.collections.Qualified`. I'll try to fix it there, but not sure if I would be able to. So IMO those quick dirty fixes should do for now

**Comment by myazinn** [comment]
also fixes https://github.com/zio/zio-intellij/issues/494

**Comment by hmemcpy** [comment]
Thank you so much for this!
